version: '3.8'

services:
  # Serviço da API Node.js
  api:
    build: .
    container_name: my_app_api
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_URI=mongodb://mongo:27017/gamesdb
      - PORT=5000
    ports:
      - "6000:5000" # Host:Container — API exposta na 6000 no host
    # volumes:
    #   - ./src:/usr/src/app/src  # opcional para desenvolvimento
    networks:
      - app-network
    depends_on:
      - mongo

  # Serviço do Banco de Dados (MongoDB)
  mongo:
    image: mongo:6
    container_name: my_app_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

# Define as redes e volumes
networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local